name: tictactoy
version: '1.0.2'
summary: Simple TIC-TAC-toe game
description: |
  A simple TIC-TAC-toe game. Get ahead of your opponent by first filling in the fields horizontally, vertically, or diagonally. Don't let your opponent do the same!
icon: data/icons/128/com.github.alexkdeveloper.tictactoy.png
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

slots:
    dbus-daemon:
        interface: dbus
        bus: session
        name: com.github.alexkdeveloper.tictactoy.desktop

apps:
    tictactoy:
        command: desktop-launch com.github.alexkdeveloper.tictactoy
        slots: [ dbus-daemon ]
        desktop: usr/share/applications/com.github.alexkdeveloper.tictactoy.desktop
        plugs: [home, x11, gsettings]

parts:
    granite:
        plugin: cmake
        source: https://github.com/elementary/granite.git
        source-tag: '6.2.0'
        configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_INSTALL_LIBDIR=/usr/lib]
        build-packages:
          - build-essential
          - valac
        stage-packages:
          - valac-0.48-vapi
    tictactoy:
        after: [granite, desktop-gtk3]
        source: https://github.com/alexkdeveloper/tictactoy.git
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
        build-packages:
            - build-essential
            - valac
            - intltool
            - libgee-0.8-dev
            - debhelper
            - libgtk-3-dev
            - libgranite-dev
            - libgtksourceview-3.0-dev
        stage-packages:
            - gnome-keyring
            - gobject-introspection
            - libgdk-pixbuf2.0-0
            - libgee-0.8-2
            - libgtk-3-0
