name: tictactoy
grade: stable
version: 1.0.0
summary: Simple TIC-TAC-toe game
description: A simple TIC-TAC-toe game. Get ahead of your opponent by first filling in the fields horizontally, vertically, or diagonally. Don't let your opponent do the same!
icon: data/icons/24/com.github.alexkdeveloper.tictactoy.png
license: GPL-3.0+

base: core18
confinement: strict

apps:
  tictactoy:
    command: usr/bin/com.github.alexkdeveloper.tictactoy
    extensions: [gnome-3-28]
    plugs:
      - home
    slots:
      - dbus-daemon
    common-id: com.github.alexkdeveloper.tictactoy

parts:
  tictactoy:
    plugin: meson
    source: https://github.com/alexkdeveloper/tictactoy.git
    source-branch: main
    meson-parameters: [--prefix=/snap/tictactoy/current/usr]
    organize:
      snap/tictactoy/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.alexkdeveloper.tictactoy.appdata.xml]

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.alexkdeveloper.tictactoy
